[simulation]
title = "LiteBIRD's beam inclination angle simulation"
description = ""
database = ""
runs = 20
angles = [0]
planets = [
    "neptune",
    "uranus"
]
frequencies = [
    "low",
    "mid",
    "high"
]
eccentricity = 0.1

[simulation.info]
author = "The LiteBIRD team"
date = true

[settings]
loggerdebug = true
datadebug = true
clear_maps = true
save_error_map = true
save_hitmap = false

[database]
active = false
name = "final_simulations"

#Solo idee di possibili parametri, eventualmente da aggiungere al report  (alcuni tramite l'oggetto lbs.Simulation)
