[simulation]
title = "LiteBIRD's beam inclination angle simulation"
description = ""
database = ""
runs = 200
angles = [0]
planets = [
    "jupiter",
    "neptune",
    "uranus"
]
frequencies = [
    "mid"
]
eccentricity = 0.1

[simulation.info]
author = "The LiteBIRD team"
date = true

[settings]
debug = true
clear_maps = true

[database]
active = false
name = "final_simulations"

#Solo idee di possibili parametri, eventualmente da aggiungere al report  (alcuni tramite l'oggetto lbs.Simulation)