[simulation]
title = "LiteBIRD's beam inclination angle simulation"
description = ""
runs = 15
angles = [0,10,20,30,40,50,60,70,80,90,100,110,120,130,140,150,160,170,180]
planets = [
    "jupiter",
    "neptune",
    "uranus"
]
frequencies = [
    "low",
    "mid",
    "high"
]

[simulation.info]
author = "The LiteBIRD team"
date = true

[settings]
debug = true
database = true

#Solo idee di possibili parametri, eventualmente da aggiungere al report  (alcuni tramite l'oggetto lbs.Simulation)