[simulation]
title = "LiteBIRD's beam inclination angle simulation"
description = ""
database = ""
runs = 200
angles = [0,20,45,90,135,180]
planets = [
    "jupiter",
    "neptune",
    "uranus"
]
frequencies = [
    "low",
    "mid",
    "high"
]
eccentricity = 0.05

[simulation.info]
author = "The LiteBIRD team"
date = true

[settings]
loggerdebug = true
datadebug = true
clear_maps = true
save_error_map = false
save_hitmap = false

[database]
active = true
name = "final_simulations2"

#Solo idee di possibili parametri, eventualmente da aggiungere al report  (alcuni tramite l'oggetto lbs.Simulation)