[simulation]
title = "LiteBIRD's beam inclination angle simulation"
description = ""
runs = 15
angles = [0,20,40,60,80,100,120,140,160,180]
planets = [
    "jupiter",
    "neptune",
    "uranus"
]
frequencies = [
    "low",
    "mid",
    "high"
]

[simulation.info]
author = "The LiteBIRD team"
date = true

[settings]
debug = false
database = true

#Solo idee di possibili parametri, eventualmente da aggiungere al report  (alcuni tramite l'oggetto lbs.Simulation)