[simulation]
base_path = "./results/"
num_of_mc_runs = 200

[planet]
planet_name = "uranus"
sed_file_name = "sed_files/uranus_sed_ghz_k.csv"
planet_radius_m = 25362000.0
scanning_simulation = "./litebird-scanning-strategy"

[detector]
channel_obj = "/releases/v1.0/satellite/MFT/M2-166/channel_info"
bandwidth_ghz = 12.0
sampling_rate_hz = 1.0
eccentricity = 0.1
frequency = "mid"
inclination = 0
