[simulation]
base_path = "./results/"
num_of_mc_runs = 20

[planet]
planet_name = "neptune"
sed_file_name = "sed_files/neptune_hf2.csv"
planet_radius_m = 24622000.0
scanning_simulation = "./scanning_strategies/neptune/"

[detector]
channel_obj = "/releases/v1.0/satellite/MFT/M2-166/channel_info"
sampling_rate_hz = 1.0
eccentricity = 0.1
frequency = "mid"
inclination = 0
