[simulation]
base_path = "./results/"
num_of_mc_runs = 20

[planet]
planet_name = "jupiter"
sed_file_name = "sed_files/jupiter_sed_ghz_k.csv"
planet_radius_m = 71492000.0
scanning_simulation = "./litebird-scanning-strategy"

[detector]
channel_obj = "/releases/v1.0/satellite/LFT/L1-040/channel_info"
bandwidth_ghz = 12.0
sampling_rate_hz = 1.0
eccentricity = 0.3
frequency = "low"
inclination = 0
